// The list. One challenge per line.
// A line starting with # is a section header, for your eyes only.
// *asterisks* make italics. A URL at the end of a line becomes the MORE button.
// Edit with editor.html, export, and replace this file.

window.PROMPT_SOURCE = [
  "# ---------- LIBRARIES AND BOOKS ----------",
  "Pick a book in your home that you haven't read and read two pages of it (from anywhere in the book).",
  "Have a conversation where you ask for a book recommendation.",
  "Read the first page of at least five books, then read the first 10 pages of the one you like the best.",
  "Find the oldest book you can, open it to the middle, and read the entire page.",
  "Look up your last name on Google Maps and find a place with your name.",
  "Look up a book you love and find someone's \"if you liked that, try this\" rec.",
  "Read the entire copyright page of the book nearest you.",
  "Put a book you've finished somewhere for a stranger to find it.",
  "",
  "# ---------- AUTHORS, ESSAYS, POEMS ----------",
  "Read any of James Marriott's weekly essays on Substack.  https://jmarriott.substack.com",
  "Read *I Think LLMs Will Prove to Be Consequential Enterprise Software*  by Freddie deBoer. Consider how you agree and disagree with him.  https://freddiedeboer.substack.com/p/i-think-llms-will-prove-to-be-consequential",
  "Read the essay *Are We City-Dwellers or Hunter Gatherers?* by David Graber and David Wengrow.  https://davidgraeber.org/articles/are-we-city-dwellers-or-hunter-gatherers/",
  "Read David Graeber on bullshit jobs. Then write down the part of your own job you'd actually defend.",
  "Go to **Arts & Letters Daily** and follow any link.  https://www.aldaily.com",
  "Paste some of these vintage ***menko*** cards into an image translator and read them.  https://i.etsystatic.com/64620079/r/il/5d0750/8339008417/il_1588xN.8339008417_i19l.jpg",
  "Read the poem *Failing and Flying* by Jack Gilbert.  https://poets.org/poem/failing-and-flying",
  "Read the poem *Going There* by Jack Gilbert.  https://poets.org/poem/going-there",
  "Read the poem *Heart and Clock* by Charles Reznikoff.  https://voetica.com/poem/14567",
  "Read the poem *Crossing Brooklyn Ferry* by Walt Whitman.  https://www.poetryfoundation.org/poems/45470/crossing-brooklyn-ferry",
  "Read these two pages from *Thor #143* by Stan Lee and Jack Kirby **out loud**.  https://drive.google.com/file/d/158QviLgVZDqOLxDNOkQeOys1LYUH73eG/view?usp=sharing",
  "Listen to Episode 1 (or read the transcript) of *A History of Rock in 500 Songs*.  https://500songs.com/podcast/flying-home-by-the-benny-goodman-sextet/",
  "Read any poem by Joy Harjo.  https://www.poetryfoundation.org/poets/joy-harjo",
  "Read any poem by Layli Long Soldier.  https://www.poetryfoundation.org/poets/layli-long-soldier",
  "Read a poem by Natalie Diaz.  https://www.poetryfoundation.org/poets/natalie-diaz",
  "Read this excellent essay about *The Eagles - Their Greatest Hits (1971–1975)*.  https://pitchfork.com/reviews/albums/the-eagles-their-greatest-hits-1971-1975/",
  "Read the 1939 essay *All You Can Hold for Five Bucks* by Joseph Mitchell.  https://medium.com/@Beefsteak/all-you-can-hold-for-five-bucks-dc945bba60d",
  "Read the poem *Calling Things What They Are* by Ada Limon.  https://www.poetryfoundation.org/poems/162174/calling-things-what-they-are",
  "Read this 1979 poem by James Tate.  https://drive.google.com/file/d/14EuxrE25fwtJ7ChItx-MfbB3po7u8mgw/view?usp=sharing",
  "Read any Ursula K. Le Guin essay online that looks interesting.",
  "Read the poem *Between Us And* by Anne Carson.  https://www.poetryfoundation.org/poems/158327/between-us-and",
  "Read one Eduardo Galeano fragment. They take two minutes each.",
  "Read Aram Saroyan's poem *lighght* and consider a defense for it.  https://www.poetryfoundation.org/poems/1595962/lighght",
  "Read a sample of Adrian Tchaikovsky's *Children of Time*.",
  "Read the short story *The Things* by Peter Watts.  https://clarkesworldmagazine.com/watts_01_10/",
  "Open Kevin Kelly's *Best Magazine Articles Ever* and read any one essay.  https://kk.org/cooltools/best-magazine-articles-ever/",
  "Read the essay *Frank Sinatra Has a Cold*.  https://classic.esquire.com/article/19660401106/print",
  "Read the Hunter S. Thompson essay *The Kentucky Derby is Decadent and Depraved*.  http://brianb.freeshell.org/a/kddd.pdf",
  "Read an essay from this list, from the decade you were born.  https://kk.org/cooltools/best-magazine-articles-ever/",
  "Copy out by hand a short paragraph or poem that you love.",
  "Read John Jeremiah Sullivan's essay *Feet in Smoke*.  https://oxfordamerican.org/magazine/issue-21-22-summer-1998/feet-in-smoke",
  "Read John Jeremiah Sullivan's *Mister Lytle*.  https://www.theparisreview.org/letters-essays/6048/mister-lytle-an-essay-john-jeremiah-sullivan",
  "Read the Wikipedia page for the year *after* the year you were born.",
  "Listen to this interview with Michael Levin on consciousness and emergence,  https://www.youtube.com/watch?v=c8iFtaltX-s",
  "Listen only to **International Rare Groove Radio** for a day.  https://www.irgradio.net/",
  "",
  "# ---------- MAKE SOMETHING (after Corita Kent) ----------",
  "**Drawing exercise:** Hold a leaf in one hand. Close one eye and trace its edge with your finger, as if you're pointing at a tiny ant walking the edge. Then get paper and a pencil and draw the leaf in that same manner.",
  "**Drawing exercise:** Pick something on your desk like a mug, a stapler, a book, a water bottle. Do a line drawing of it. Stick it on the fridge.",
  "Looking exercise: Cut a very small rectangular hole in a piece of cardstock or heavy paper. Spend 10 minutes looking through it to frame what you see.",
  "**Drawing exercise:** Copy something exactly, by hand. A label, a logo, a page. No erasing. Mistakes are fine!",
  "**Photo prompt:** Photograph ten signs. Crop each one down to just the words.",
  "**Photo prompt:** Go to a gas station or a supermarket and find something with awesome packaging. Take a picture.",
  "**Photo prompt:** Photograph the same thing (or person) from five different distances or angles. Afterwards, think about which images are more compelling, and why.",
  "**Drawing exercise:** Draw a copy of a photo by turning it upside down and looking at the shapes and lines, not the subject matter.",
  "**Drawing Prompt:** Pick one letter off a sign or poster and try to draw it as big as your paper allows. No erasing; just redraw lines.",
  "**Writing Prompt:** Write out I AM BLESSED and list 2 or 3 things why. Tape it where you'll see it tomorrow.",
  "**Drawing Prompt:** Draw the same object three times: fast, slow, and without looking at the paper. No erasing; just redraw lines.",
  "**Drawing Prompt:** Find the ugliest thing in your kitchen and draw a picture of it. No erasing; just redraw lines.",
  "**Drawing Prompt:** Draw your hand with your other hand. No erasing; just redraw lines.",
  "**Photo Prompt:** Look at a crack, stain, or rust patch, then take a photo.",
  "**Thinking prompt:** if you were going to make a zine, what would it be? Share your idea with a friend.",
  "Make a collaborative 12-song playlist with a friend, taking turns adding one song at a time.",
  "Make a postcard out of paper, stickers, photos, whatever, and send it to someone.",
  "Make a \"memory box\" out of a coffee can, small cardboard box, or container. Decorate it. Write something you did last week, fold it up and add it. Write something you did today, fold it up and add it. Put it somewhere where you remember to add to it.",
  "Type a message really fast this week and send it without correcting any of the autocorrects.",
  "",
  "# ---------- BEER ----------",
  "Go for a walk while listening to Herbie Hancock's entire album *Thrust* on ear buds.",
  "Buy a drink  for someone who looks like they're having a bad day.",
  "Go to a bar where you don't speak the language.",
  "Set a timer for 5 minutes. Find a cool beer label online and save it to your Pictures.",
  "Go to diffords.com and find a new cocktail to make.",
  "Go to the oldest local-ish bar you can find.",
  "Have a proper lunch—something you've made—on a weekday. Sit at a table, not at your desk.",
  "Take one beer outside at dusk and watch it get dark.",
  "Buy a bottle or can of something you've never heard of.",
  "Drink a beer somewhere you've never had one.",
  "",
  "# ---------- SCREENS OFF ----------",
  "Plan a 24-hour screen-free day. Think about what you'll do instead.",
  "Listen to an album all the way through with no screens or phone.",
  "Put your phone in a drawer until dinner.",
  "Look up best recent jazz or classical releases on AllMusic. Pick one and listen to it while doing something else.",
  "Look up new releases on AllMusic, Pitchfork, or elsewhere. Pick one and listen to it while doing other stuff.",
  "Leave your phone at home while you run an errand.",
  "Unsubscribe from ten emails. Do it!",
  "Spend some time finding the saddest song you can. Not \"cheesy sad\" but something that moves you.",
  "Listen to an album you loved in high school.",
  "Set a reminder now to get up an hour earlier than usual tomorrow and go for a walk.",
  "",
  "# ---------- CHEAP FOOD ----------",
  "Make a cheap lunch plan with someone for next week.",
  "Find somewhere you can eat lunch for under five dollars.",
  "Buy a very cheap thing in a store you've never entered.",
  "Buy an instant noodle brand you've never bought.",
  "Plan to make one of the New York Time's *50 Most Popular Recipes of All Time*.  https://cooking.nytimes.com/68861692-nyt-cooking/13395693-our-50-most-popular-recipes-of-all-time-so-far",
  "Buy a single piece of fruit and eat it before you get home.",
  "Make a recipe with a maximum of three ingredients. (Water doesn't count, and it's up to you whether salt counts.)",
  "Eat at a food truck or vendor you've never been to before.",
  "This week, try a cuisine you've never had.",
  "Ask someone else to order for you at mealtime.",
  "Cook a recipe from the back of a package.",
  "Make a Korean corn-omelet sandwich: fry two bread slices in butter. Beat 2 eggs with a lot of corn and cook it like an omelet. Optionally add a slice or cheese and/or a slice of ham. Garnish with chopped cabbage, ketchup (or hot sauce) and mayo.",
  "",
  "# ---------- YOUR CITY, ON FOOT ----------",
  "Plan a day-long walk across your city. You don't have to do it. Just plan it!",
  "Go inside an interesting building and look around. Take a photo and text it to a friend or family member.",
  "Ride a bus or train to the end of the line and explore.",
  "Walk along your street until you get to something you haven't noticed before, and take a picture, go inside, explore ... whatever makes sense.",
  "Find a nearby old cemetery or walled garden and sit in for fifteen minutes. Music ok, but not scrolling.",
  "Find a piece of public art near you and spend some time thinking about it. If it makes no sense, enjoy the absurdity that someone made something that makes no sense.",
  "Do one lap of a nearby big park.",
  "Walk to the highest point you can reach on foot, and be there at dusk.",
  "Walk a street you know well and count what wasn't there five years ago.",
  "Go inside a train station or airport even though you're not going anywhere.",
  "Walk a stretch of the nearest river, canal or creek path you've never walked.",
  "Find a building you like and photograph it: some big views and some closeup details. Then look up who built it or lived there.",
  "Walk every street inside a three-block square.",
  "Explore an unfamiliar neighborhood.",
  "**Photo prompt:** Go on a photo walk. Take pictures of banal things.",
  "**Photo prompt:** Go on a photo walk. Take pictures of architectural details only.",
  "**Photo prompt:** Go on a photo walk. Take nature close-ups.",
  "Go on a walk. Count how many animals (including pets) that you see.",
  "If you see someone taking a picture, ask if they want you in the picture, assuming they do.",
  "Walk somewhere you usually drive to.",
  "Watch someone working and strike up a conversation about what they're doing.",
  "Find a set of outdoor stairs and go up them.",
  "Next time you drive somewhere, park at the furthest end of the parking lot.",
  "",
  "# ---------- YOUR CITY, BY CAR ----------",
  "Drive or walk to the far end of your area and get a cheap lunch somewhere.",
  "Go somewhere with a view and stay twenty minutes.",
  "Go to a different grocery store than the one you usually go to.",
  "",
  "# ---------- PEOPLE, NO JOINING REQUIRED ----------",
  "Send a postcard to someone. You can do it! If you don't have one, make one.",
  "Visit a shop you've never been into and strike up a conversation.",
  "If you're about to text someone, call them instead.",
  "Have a conversation where you just mirror what they're saying. They'll think you're an amazing listener!",
  "Send a photo to one person with no caption.",
  "Plan a prank. Bonus points for executing it.",
  "If you like a stranger's hair, t-shirt, shoes, outfit, whatever ... say so!",
  "Learn the name of someone you see every week and have never asked. Or admit to them that you forgot their name and ask them again.",
  "Mail something (anything) to someone (anyone).",
  "Say yes to the next small thing you were going to decline.",
  "Ask someone for help with something.",
  "Ask somebody to run an errand with you.",
  "Introduce yourself to a neighbor you've never spoken to.",
  "Say hello first, all day, to everybody.",
  "Tell one person exactly why you like working with them.",
  "Go online, find a cool (or ridiculous, or vintage) refrigerator magnet, buy it, and send it anonymously to a friend.",
  "Buy an unused vintage postcard off of eBay. When it arrives, send it to someone.",
  "",
  "# ---------- THE HOUSE / THE MOOD ----------",
  "Write down three things bothering you, then burn the paper in the sink.",
  "Take a shower in the middle of the day and put on different clothes.",
  "Throw away five things you won't miss.",
  "Wash something that's been sitting there (like a dish or dirty shirt).",
  "Sit in a spot you never sit in and read for fifteen minutes.",
  "Do nothing for ten minutes.",
  "Stretch for five minutes.",
  "Be naked! Spend some time indoors in private without clothes on.",
  "Hang something that's been rolled up in the corner.",
  "Take a couple pictures of the inside of your house so that In twenty years you'll have a record of what it looked like.",
  "Reorganize a bookshelf, whether by size, color, topic, good to bad, or some other system.",
  "Move a piece of furniture and live with the new layout for a week.",
  "",
  "# ---------- WORK ----------",
  "Write down the name of a job you'd want, even if it's unattainable.",
  "Write down the best thing that happened at work this year.",
  "Ask yourself what you'd tell a colleague to do if they were in your present situation. Then do that.",
  "Finish that lingering thing that's ninety percent done.",
  "Write an email you've been avoiding. It can just be 2-3 sentences.",
  "Cancel a subscription you don't need.",
  "",
  "# ---------- LEARN SOMETHING ----------",
  "Learn the species of a tree on your block.",
  "Watch *Aguirre, the Wrath of God*.",
  "Watch episode 1 of *My Mister* on Netflix.",
  "Look up repertory cinema listings and pick a film for the next two weeks.",
  "Look up the history of your street name.",
  "Write a list of three things you have to do. Then rewrite the the list, changing \"have\" to \"get\".",
  "Buy a cheap-ass plant that's hard to kill. Make it a mission for the next month. Set reminders on your phone.",
  "Learn five words in a language you'll never need. Practice them every morning this week.",
  "Discuss the ethics of communicating with octopuses with Claude or ChatGPT.",
  "Learn to tie a cool knot.",
  "Find out what birds are outside your window or in your neighborhood.",
  "Learn how something you use every day works.",
  "Search for highlights from a recent rugby game and watch them.",
  "Go to ChatGPT and ask it to *concisely* explain a philosophical, religious or belief system of your choice. If you can't think of one, try igtheism or panpsychism. Tell it to keep it short and that you'll ask follow-up questions if needed.  https://chatgpt.com/",
  "Write down five things you'd do with a free Saturday. Put the list on your fridge.",
  "Write down eight skills you have. Not subjective ones like \"I'm a good gift-giver\" but concrete ones like \"I know CPR.\" or \"I can poach eggs.\"",
  "Pick one of your favorite animals (as in \"hippo\", \"otter\", etc) and read about it on Wikipedia until you learn three really cool things you didn't know.",
  "Pick a vegetable or herb at the market that you've never cooked. Find a simple recipe and try it.",
  "",
  "# ---------- OUTSIDE, DOING NOTHING ----------",
  "Make a hot beverage in the morning and go for a walk.",
  "Make Spanish hot chocolate tonight: It's a small hot chocolate with cornstarch added as a thickener.",
  "Drink tea today instead of coffee. Or vice versa.",
  "Get yourself outside within ten minutes of waking up.",
  "Watch any animal—it can be your pet—for five minutes during a time when it's not aware of you.",
  "",
  "# ---------- GO SOMEWHERE ONCE ----------",
  "Walk into a hotel lobby and sit down like you belong there.",
  "",
  "# ---------- SMALL ADJUSTMENTS ----------",
  "Take a different route to somewhere you go every day.",
  "Go through your t-shirt drawer, find a shirt you never wear, and either wear it or get rid of it.",
  "Use a good thing this week that you've been saving for a special occasion.",
  "Put five dollars in a place where you'll forget about it and be happily surprised to find it later.",
  "Pick a date two weeks out and plan something for that date.",
  "Set an alarm to remember to do something that isn't work or an obligation.",
  "Write down what a great day was like in your 20s or 30s. Think about simple things you can do to get back into that head space.",
  "Spontaneously call a family member, just to say hello and tell them you were thinking of them.",
  "",
  "# ---------- OBLIQUE, BUT DO-ABLE ----------",
  "Spontaneously call a friend, just to say hello and tell them you were thinking of them.",
  "\"If a thing is worth doing, it is worth doing badly.\"—G.K. Chesterton. Do something badly.",
  "Make a decision today by flipping a coin.",
  "Consult the *I Ching* for inspiration, guidance, or a different perspective.  https://mottstudios.github.io/i-ching/",
  "One time today, do the opposite of your first instinct.",
  "When faced with a decision today, choose the thing that results in a larger change in your life.",
  "Make something differently: a different pasta sauce, a different way to cook eggs, a different way of cooking potatoes, etc.",
  "Pick a song you like, build a radio station from it, and keep only the tracks you'd play again. Pick a different song from that playlist and do the same. Repeat, until you have a 2-3 hour playlist.",
  "Pick a color and look for it all day wherever you go.",
  "Find out where a noise is coming from.",
  "Listen to a room for two minutes with your eyes closed.",
  "Sit somewhere and people-watch for 15-20 minutes.",
  "Do a crossword puzzle. If it's online, print it out.",
  "**Photo prompt:** Take a photo of something people don't usually photograph.",
  "**Photo prompt:** Choose one object and look at it until you notice something new.",
  "Find the oldest thing you own and hold it for a minute.",
  "Throw away a thing you keep moving from place to place.",
  "Pick two numbers, ***a*** and ***b***. Open a book to page ***a*** and read line ***b***.",
  "Do what the most patient person you know would do right now.",
  "Do the thing you'd do if you weren't tired.",
  "Leave something small and free where a stranger will find it.",
  "Leave the house with no destination. Set a timer for 11 minutes. When the alarm goes off, turn back.",
  "Make a 45-minute playlist and listen to it on a walk. When it's done, check how many steps you went.",
  "Before bed, describe your day in twelve words, then six, then two.",
  "Make a 45-minute playlist of the same song over-and-over, and listen to it on a walk. Listen to the different components of the song: lyrics, vocals, drums, etc."
].join("\n");
